/**
 * Applies pending SQL migrations from src/db/migrations (generated by
 * `npm run db:generate`). `--status` only reports. Never edits the schema
 * by inference: drizzle-kit generate is the only thing that writes migrations.
 */
import { migrate } from 'drizzle-orm/postgres-js/migrator'
import { readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { createDb } from './client.js'

const here = dirname(fileURLToPath(import.meta.url))
export const MIGRATIONS_DIR = join(here, 'migrations')

export async function runMigrations(databaseUrl: string, { statusOnly = false } = {}) {
  const { db, client, close } = createDb(databaseUrl, { max: 1 })
  try {
    const files = readdirSync(MIGRATIONS_DIR).filter((f) => f.endsWith('.sql')).sort()
    const applied = await client`
      select hash from drizzle.__drizzle_migrations
    `.catch(() => [] as { hash: string }[])
    const pending = Math.max(0, files.length - applied.length)
    if (statusOnly) return { files: files.length, applied: applied.length, pending }
    await migrate(db, { migrationsFolder: MIGRATIONS_DIR })
    return { files: files.length, applied: files.length, pending: 0 }
  } finally {
    await close()
  }
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]
if (isMain) {
  const url = process.env.DATABASE_URL
  if (!url) {
    console.error('DATABASE_URL is not set')
    process.exit(2)
  }
  const statusOnly = process.argv.includes('--status')
  runMigrations(url, { statusOnly })
    .then((r) => {
      console.log(JSON.stringify(r))
      if (statusOnly && r.pending > 0) process.exit(4)
    })
    .catch((e) => {
      console.error(e)
      process.exit(1)
    })
}
