[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["dependencies"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
via_ir = false

[dependencies]
"@openzeppelin-contracts" = "5.4.0"
